import type {
  AnalysisProvider,
  AnalyzeResumeForJobInput,
  AnalyzeResumeForJobResult,
} from "@/lib/ai/providers/types";

export class MockAnalysisProvider implements AnalysisProvider {
  async analyzeResumeForJob(
    input: AnalyzeResumeForJobInput,
  ): Promise<AnalyzeResumeForJobResult> {
    return {
      analysis: {
        fitScore: 78,
        summary:
          "This is a mock analysis. The resume appears to match several key parts of the job description, but some requirements need stronger evidence.",
        strongMatches: [
          "The resume shows relevant full-stack development experience.",
          "The resume includes TypeScript and React experience.",
        ],
        gaps: [
          "The job description may require more explicit cloud deployment experience.",
          "The resume could show testing experience more clearly.",
        ],
        suggestedResumeImprovements: [
          "Add a bullet that quantifies full-stack project impact.",
          "Mention specific testing tools if they were used.",
        ],
        caveats: [
          "This result was generated by a mock provider and does not analyze the actual text deeply.",
          `Resume length: ${input.resumeText.length} characters.`,
          `Job description length: ${input.jobDescriptionText.length} characters.`,
        ],
      },
      modelMetadata: {
        provider: "mock",
        model: "mock-resume-job-analysis-v1",
        isMock: true,
      },
    };
  }
}